[package]
name = "plothan/vinum"
version = "0.3.0-dev"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A multi-paradigm, fast and modern reactive state management library."
include = ["src", "default.project.json"]

[dependencies]